### ISSUE TITLE
Error: "Declaring or accessing a prop starting with `$$` is illegal"

### ISSUE THREAD

**Issue by DrZlo13** [svar-widgets/filemanager#1]
I'm trying to use the file manager component in my project, but the svelte compiler keeps throwing errors.
What I do:
```
> npm create vite
✔ Project name: … svelte-lamp
✔ Select a framework: › Svelte
✔ Select a variant: › TypeScript
> cd svelte-lamp
> npm install wx-svelte-filemanager
```
then add `import { Filemanager } from "wx-svelte-filemanager";` just like in the tutorial.

```
> npm run dev

> svelte-lamp@0.0.0 dev
> vite

Forced re-optimization of dependencies

  VITE v5.4.10  ready in 310 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] node_modules/wx-svelte-filemanager/src/themes/Willow.svelte:3:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-filemanager/src/themes/Willow.svelte:3:23:
      3 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-filemanager/src/index.js:4:19:
      4 │ import Willow from "./themes/Willow.svelte";
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-filemanager/src/themes/Material.svelte:3:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-filemanager/src/themes/Material.svelte:3:23:
      3 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-filemanager/src/index.js:3:21:
      3 │ import Material from "./themes/Material.svelte";
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-filemanager/src/themes/WillowDark.svelte:3:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-filemanager/src/themes/WillowDark.svelte:3:23:
      3 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-filemanager/src/index.js:5:23:
      5 │ import WillowDark from "./themes/WillowDark.svelte";
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-core/src/components/Button.svelte:12:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-core/src/components/Button.svelte:12:23:
      12 │  const SLOTS = $$props.$$slots;
         ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-core/src/index.js:4:34:
      4 │ export { default as Button } from "./components/Button.svelte";
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-core/src/components/Icon.svelte:5:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-core/src/components/Icon.svelte:5:23:
      5 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-core/src/index.js:13:32:
      13 │ export { default as Icon } from "./components/Icon.svelte";
         ╵                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-core/src/themes/Willow.svelte:6:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-core/src/themes/Willow.svelte:6:23:
      6 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-core/src/index.js:41:34:
      41 │ export { default as Willow } from "./themes/Willow.svelte";
         ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-core/src/themes/Material.svelte:6:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-core/src/themes/Material.svelte:6:23:
      6 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-core/src/index.js:40:36:
      40 │ export { default as Material } from "./themes/Material.svelte";
         ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-core/src/themes/WillowDark.svelte:6:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-core/src/themes/WillowDark.svelte:6:23:
      6 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-core/src/index.js:42:38:
      42 │ export { default as WillowDark } from "./themes/WillowDark.svelte";
         ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-core/src/components/TwoState.svelte:23:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-core/src/components/TwoState.svelte:23:23:
      23 │  const SLOTS = $$props.$$slots;
         ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-core/src/index.js:34:36:
      34 │ export { default as TwoState } from "./components/TwoState.svelte";
         ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-core/src/components/RichSelect.svelte:13:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-core/src/components/RichSelect.svelte:13:23:
      13 │  const SLOTS = $$props.$$slots;
         ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-core/src/index.js:20:38:
      20 │ export { default as RichSelect } from "./components/RichSelect.svelte";
         ╵                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-menu/src/components/ContextMenu.svelte:4:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-menu/src/components/ContextMenu.svelte:4:23:
      4 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-menu/src/index.js:4:24:
      4 │ import ContextMenu from "./components/ContextMenu.svelte";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-menu/src/components/ActionMenu.svelte:10:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-menu/src/components/ActionMenu.svelte:10:23:
      10 │  const SLOTS = $$props.$$slots;
         ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-menu/src/index.js:5:23:
      5 │ import ActionMenu from "./components/ActionMenu.svelte";
        ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-grid/src/themes/WillowDark.svelte:3:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-grid/src/themes/WillowDark.svelte:3:23:
      3 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-grid/src/index.js:10:23:
      10 │ import WillowDark from "./themes/WillowDark.svelte";
         ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-grid/src/themes/Willow.svelte:3:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-grid/src/themes/Willow.svelte:3:23:
      3 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-grid/src/index.js:9:19:
      9 │ import Willow from "./themes/Willow.svelte";
        ╵                    ~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] node_modules/wx-svelte-grid/src/themes/Material.svelte:3:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals) [plugin vite-plugin-svelte:optimize-svelte]

    node_modules/wx-svelte-grid/src/themes/Material.svelte:3:23:
      3 │  const SLOTS = $$props.$$slots;
        ╵                        ^

  The plugin "vite-plugin-svelte:optimize-svelte" was triggered by this import

    node_modules/wx-svelte-grid/src/index.js:8:21:
      8 │ import Material from "./themes/Material.svelte";
        ╵                      ~~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/dev_user/work/busy/svelte-lamp/node_modules/esbuild/lib/main.js:1472
  let error = new Error(text);
              ^

Error: Build failed with 15 errors:
node_modules/wx-svelte-core/src/components/Button.svelte:12:23: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/wx-svelte-core/src/components/Button.svelte:12:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals)
node_modules/wx-svelte-core/src/components/Icon.svelte:5:23: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/wx-svelte-core/src/components/Icon.svelte:5:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals)
node_modules/wx-svelte-core/src/components/RichSelect.svelte:13:23: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/wx-svelte-core/src/components/RichSelect.svelte:13:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals)
node_modules/wx-svelte-core/src/components/TwoState.svelte:23:23: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/wx-svelte-core/src/components/TwoState.svelte:23:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals)
node_modules/wx-svelte-core/src/themes/Material.svelte:6:23: ERROR: [plugin: vite-plugin-svelte:optimize-svelte] node_modules/wx-svelte-core/src/themes/Material.svelte:6:23 Declaring or accessing a prop starting with `$$` is illegal (they are reserved for Svelte internals)
...
    at failureErrorWithLog (/Users/dev_user/work/busy/svelte-lamp/node_modules/esbuild/lib/main.js:1472:15)
    at /Users/dev_user/work/busy/svelte-lamp/node_modules/esbuild/lib/main.js:945:25
    at /Users/dev_user/work/busy/svelte-lamp/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v18.18.0
```

**Comment by mkozhukh** [comment]
Yes, we are aware, and we are updating core libs now with the plan to fix the Gantt as well later
The Svelte 5 compatible version will be available till the end of the November

**Comment by mkozhukh** [comment]
We have just published `wx-svelte-filemanager@2.0.0-beta-2`, which is compatible with Svelte 5.x.
The final version and updated documentation will be available in the next few days.
